### ISSUE TITLE
Deploy to Netlify

### ISSUE THREAD

**Issue by xhijack** [ezhmd/posty-poster#3]
Your project is awesome. I am going to deploy to netlify. But always failed. did you know how to deploy your project to netlify. Coz when I deployed it showed not found page.

thanks

**Comment by ezhmd** [comment]
Thanks, unfortunately I've never tried deploying this project to Netlify.

**Comment by ezhmd** [comment]
Netlify looks interesting though. I might use it in the future. Or can you help me make this project work with Netlify?

**Comment by xhijack** [comment]
It work for poster app but for data it didin't work. So I deployed different server. But the problem is Cross Domain so I used cors.io :D

**Comment by ezhmd** [comment]
I see, if you can change the CORS header of your data server it will be better. Cors.io often has over quota issue. Also, the performance will be better because the data doesn't have to go around another server.

**Comment by xhijack** [comment]
I add CORS in .httaccess coz I am using cpanel. And it works :D

**Comment by ezhmd** [comment]
Great! Glad to know it worked.

**Comment by argelcandelaria** [comment]
@xhijack can you help me deploy this web app. I don't know how :(

**Comment by argelcandelaria** [comment]
@xhijack can you teach me how did you deploy it on netlify together with the backend server

**Comment by xhijack** [comment]
@argelcandelaria you need a hosting and activate the CORS. You can setup by .httaccess or other other alternative and you can't deploy on netlify. Netlify worked for frontend only

**Comment by argelcandelaria** [comment]
i try to deploy it using the forked github of posty poster, it did work.

**Comment by argelcandelaria** [comment]
i don't get it on how to activate the CORS?

**Comment by argelcandelaria** [comment]
can you teach me

**Comment by ezhmd** [comment]
Hello @argelcandelaria , 
You can try this tutorial https://ma.ttias.be/set-access-control-allow-origin-cors-headers-apache-vhost-htaccess/ /
